google:
  base:
    email: "t.hashy13@gmail.com"
    pwd: "topnotto21"
  ss:
    ssid: "1uNKILtVDa8h4uLNk914mn2ecZCSQotBE3gz_auRO2u4"
    sheet_names:
      aggregate: "Aggregate"
      ts: "Works"
application:
  login:
    id: "takahiro"
    pwd: "topnotto21"